apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    {{- include "argocd-chart.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: argocd
data:
  application.instanceLabelKey: argocd.argoproj.io/instance
  server.insecure: "true"
  policy.default: role:readonly
  policy.csv: |
    p, role:admin, applications, *, */*, allow
    p, role:admin, clusters, *, *, allow
    p, role:admin, repositories, *, *, allow
    g, argocd-admins, role:admin
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  labels:
    {{- include "argocd-chart.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: argocd
data:
  server.insecure: "true"