nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  repository: quay.io/argoproj/argocd
  tag: "v2.12.6"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080
  targetPort: 8080
  nodePort: 30080

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

argocd:
  admin:
    passwordSecret:
      name: "argocd-admin-secret"
      key: "password"